### ISSUE TITLE
manifest unknown

### ISSUE THREAD

**Issue by adocampo** [randomcoww/docker-mpd#1]
Hello, 
Container fails to download, this is the error
```
Error response from daemon: manifest for randomcoww/mpd:latest not found: manifest unknown: manifest unknown
```

**Comment by randomcoww** [comment]
Thanks. I stopped using the `latest` tag for this image. I've updated the README

https://github.com/randomcoww/docker-mpd/commit/aea0871a04f162d3e2cc84d4e4e71cdfffb1fb91

**Comment by adocampo** [comment]
cool, thank you!
